import bmwPic from '@public/images/bmwf90m5.jpg';

export const DESKTOP_SIZE = 1200;

export const cars = [
  {
    pageNumber: 1,
    itemsQty: 33,
    items: [
      {
        image: bmwPic,
        make: 'BMW',
        model: '5-series',
        year: 2022,
        price: '42 000 000',
        specs: {
          type: 'Седан',
          drive: 'Передний привод',
          gearbox: 'АКПП',
          fuel: 'Бензин',
          volume: '4.4 литра',
          mileage: '2 000 км',
        },
        location: 'Сеул, Корея',
        id: '1',
      },
      {
        image: bmwPic,
        make: 'BMW',
        model: '5-series',
        year: 2022,
        price: '42 000 000',
        specs: {
          type: 'Седан',
          drive: 'Передний привод',
          gearbox: 'АКПП',
          fuel: 'Бензин',
          volume: '4.4 литра',
          mileage: '2 000 км',
        },
        location: 'Сеул, Корея',
        id: '2',
      },
      {
        image: bmwPic,
        make: 'BMW',
        model: '5-series',
        year: 2022,
        price: '42 000 000',
        specs: {
          type: 'Седан',
          drive: 'Передний привод',
          gearbox: 'АКПП',
          fuel: 'Бензин',
          volume: '4.4 литра',
          mileage: '2 000 км',
        },
        location: 'Сеул, Корея',
        id: '3',
      },
      {
        image: bmwPic,
        make: 'BMW',
        model: '5-series',
        year: 2022,
        price: '42 000 000',
        specs: {
          type: 'Седан',
          drive: 'Передний привод',
          gearbox: 'АКПП',
          fuel: 'Бензин',
          volume: '4.4 литра',
          mileage: '2 000 км',
        },
        location: 'Сеул, Корея',
        id: '4',
      },
      {
        image: bmwPic,
        make: 'BMW',
        model: '5-series',
        year: 2022,
        price: '42 000 000',
        specs: {
          type: 'Седан',
          drive: 'Передний привод',
          gearbox: 'АКПП',
          fuel: 'Бензин',
          volume: '4.4 литра',
          mileage: '2 000 км',
        },
        location: 'Сеул, Корея',
        id: '5',
      },
      {
        image: bmwPic,
        make: 'BMW',
        model: '5-series',
        year: 2022,
        price: '42 000 000',
        specs: {
          type: 'Седан',
          drive: 'Передний привод',
          gearbox: 'АКПП',
          fuel: 'Бензин',
          volume: '4.4 литра',
          mileage: '2 000 км',
        },
        location: 'Сеул, Корея',
        id: '6',
      },
      {
        image: bmwPic,
        make: 'BMW',
        model: '5-series',
        year: 2022,
        price: '42 000 000',
        specs: {
          type: 'Седан',
          drive: 'Передний привод',
          gearbox: 'АКПП',
          fuel: 'Бензин',
          volume: '4.4 литра',
          mileage: '2 000 км',
        },
        location: 'Сеул, Корея',
        id: '7',
      },
      {
        image: bmwPic,
        make: 'BMW',
        model: '5-series',
        year: 2022,
        price: '42 000 000',
        specs: {
          type: 'Седан',
          drive: 'Передний привод',
          gearbox: 'АКПП',
          fuel: 'Бензин',
          volume: '4.4 литра',
          mileage: '2 000 км',
        },
        location: 'Сеул, Корея',
        id: '8',
      },
      {
        image: bmwPic,
        make: 'BMW',
        model: '5-series',
        year: 2022,
        price: '42 000 000',
        specs: {
          type: 'Седан',
          drive: 'Передний привод',
          gearbox: 'АКПП',
          fuel: 'Бензин',
          volume: '4.4 литра',
          mileage: '2 000 км',
        },
        location: 'Сеул, Корея',
        id: '9',
      },
      {
        image: bmwPic,
        make: 'BMW',
        model: '5-series',
        year: 2022,
        price: '52 000 000',
        specs: {
          type: 'Седан',
          drive: 'Передний привод',
          gearbox: 'АКПП',
          fuel: 'Бензин',
          volume: '4.4 литра',
          mileage: '2 000 км',
        },
        location: 'Сеул, Корея',
        id: '10',
      },
      {
        image: bmwPic,
        make: 'BMW',
        model: '5-series',
        year: 2022,
        price: '22 000 000',
        specs: {
          type: 'Седан',
          drive: 'Передний привод',
          gearbox: 'АКПП',
          fuel: 'Бензин',
          volume: '4.4 литра',
          mileage: '2 000 км',
        },
        location: 'Сеул, Корея',
        id: '11',
      },
      {
        image: bmwPic,
        make: 'BMW',
        model: '5-series',
        year: 2022,
        price: '12 000 000',
        specs: {
          type: 'Седан',
          drive: 'Передний привод',
          gearbox: 'АКПП',
          fuel: 'Бензин',
          volume: '4.4 литра',
          mileage: '2 000 км',
        },
        location: 'Сеул, Корея',
        id: '12',
      },
    ],
  },
  {
    pageNumber: 2,
    itemsQty: 33,
    items: [
      {
        image: bmwPic,
        make: 'BMW',
        model: '5-series',
        year: 2022,
        price: '42 000 000',
        specs: {
          type: 'Седан',
          drive: 'Передний привод',
          gearbox: 'АКПП',
          fuel: 'Бензин',
          volume: '4.4 литра',
          mileage: '2 000 км',
        },
        location: 'Сеул, Корея',
        id: '13',
      },
      {
        image: bmwPic,
        make: 'BMW',
        model: '5-series',
        year: 2022,
        price: '42 000 000',
        specs: {
          type: 'Седан',
          drive: 'Передний привод',
          gearbox: 'АКПП',
          fuel: 'Бензин',
          volume: '4.4 литра',
          mileage: '2 000 км',
        },
        location: 'Сеул, Корея',
        id: '14',
      },
      {
        image: bmwPic,
        make: 'BMW',
        model: '5-series',
        year: 2022,
        price: '42 000 000',
        specs: {
          type: 'Седан',
          drive: 'Передний привод',
          gearbox: 'АКПП',
          fuel: 'Бензин',
          volume: '4.4 литра',
          mileage: '2 000 км',
        },
        location: 'Сеул, Корея',
        id: '15',
      },
      {
        image: bmwPic,
        make: 'BMW',
        model: '5-series',
        year: 2022,
        price: '42 000 000',
        specs: {
          type: 'Седан',
          drive: 'Передний привод',
          gearbox: 'АКПП',
          fuel: 'Бензин',
          volume: '4.4 литра',
          mileage: '2 000 км',
        },
        location: 'Сеул, Корея',
        id: '16',
      },
      {
        image: bmwPic,
        make: 'BMW',
        model: '5-series',
        year: 2022,
        price: '42 000 000',
        specs: {
          type: 'Седан',
          drive: 'Передний привод',
          gearbox: 'АКПП',
          fuel: 'Бензин',
          volume: '4.4 литра',
          mileage: '2 000 км',
        },
        location: 'Сеул, Корея',
        id: '17',
      },
      {
        image: bmwPic,
        make: 'BMW',
        model: '5-series',
        year: 2022,
        price: '42 000 000',
        specs: {
          type: 'Седан',
          drive: 'Передний привод',
          gearbox: 'АКПП',
          fuel: 'Бензин',
          volume: '4.4 литра',
          mileage: '2 000 км',
        },
        location: 'Сеул, Корея',
        id: '18',
      },
      {
        image: bmwPic,
        make: 'BMW',
        model: '5-series',
        year: 2022,
        price: '42 000 000',
        specs: {
          type: 'Седан',
          drive: 'Передний привод',
          gearbox: 'АКПП',
          fuel: 'Бензин',
          volume: '4.4 литра',
          mileage: '2 000 км',
        },
        location: 'Сеул, Корея',
        id: '19',
      },
      {
        image: bmwPic,
        make: 'BMW',
        model: '5-series',
        year: 2022,
        price: '42 000 000',
        specs: {
          type: 'Седан',
          drive: 'Передний привод',
          gearbox: 'АКПП',
          fuel: 'Бензин',
          volume: '4.4 литра',
          mileage: '2 000 км',
        },
        location: 'Сеул, Корея',
        id: '20',
      },
      {
        image: bmwPic,
        make: 'BMW',
        model: '5-series',
        year: 2022,
        price: '42 000 000',
        specs: {
          type: 'Седан',
          drive: 'Передний привод',
          gearbox: 'АКПП',
          fuel: 'Бензин',
          volume: '4.4 литра',
          mileage: '2 000 км',
        },
        location: 'Сеул, Корея',
        id: '21',
      },
      {
        image: bmwPic,
        make: 'BMW',
        model: '5-series',
        year: 2022,
        price: '42 000 000',
        specs: {
          type: 'Седан',
          drive: 'Передний привод',
          gearbox: 'АКПП',
          fuel: 'Бензин',
          volume: '4.4 литра',
          mileage: '2 000 км',
        },
        location: 'Сеул, Корея',
        id: '22',
      },
      {
        image: bmwPic,
        make: 'BMW',
        model: '5-series',
        year: 2022,
        price: '42 000 000',
        specs: {
          type: 'Седан',
          drive: 'Передний привод',
          gearbox: 'АКПП',
          fuel: 'Бензин',
          volume: '4.4 литра',
          mileage: '2 000 км',
        },
        location: 'Сеул, Корея',
        id: '23',
      },
      {
        image: bmwPic,
        make: 'BMW',
        model: '5-series',
        year: 2022,
        price: '42 000 000',
        specs: {
          type: 'Седан',
          drive: 'Передний привод',
          gearbox: 'АКПП',
          fuel: 'Бензин',
          volume: '4.4 литра',
          mileage: '2 000 км',
        },
        location: 'Сеул, Корея',
        id: '24',
      },
    ],
  },
  {
    pageNumber: 3,
    itemsQty: 33,
    items: [
      {
        image: bmwPic,
        make: 'BMW',
        model: '5-series',
        year: 2022,
        price: '42 000 000',
        specs: {
          type: 'Седан',
          drive: 'Передний привод',
          gearbox: 'АКПП',
          fuel: 'Бензин',
          volume: '4.4 литра',
          mileage: '2 000 км',
        },
        location: 'Сеул, Корея',
        id: '25',
      },
      {
        image: bmwPic,
        make: 'BMW',
        model: '5-series',
        year: 2022,
        price: '42 000 000',
        specs: {
          type: 'Седан',
          drive: 'Передний привод',
          gearbox: 'АКПП',
          fuel: 'Бензин',
          volume: '4.4 литра',
          mileage: '2 000 км',
        },
        location: 'Сеул, Корея',
        id: '26',
      },
      {
        image: bmwPic,
        make: 'BMW',
        model: '5-series',
        year: 2022,
        price: '42 000 000',
        specs: {
          type: 'Седан',
          drive: 'Передний привод',
          gearbox: 'АКПП',
          fuel: 'Бензин',
          volume: '4.4 литра',
          mileage: '2 000 км',
        },
        location: 'Сеул, Корея',
        id: '27',
      },
      {
        image: bmwPic,
        make: 'BMW',
        model: '5-series',
        year: 2022,
        price: '42 000 000',
        specs: {
          type: 'Седан',
          drive: 'Передний привод',
          gearbox: 'АКПП',
          fuel: 'Бензин',
          volume: '4.4 литра',
          mileage: '2 000 км',
        },
        location: 'Сеул, Корея',
        id: '28',
      },
      {
        image: bmwPic,
        make: 'BMW',
        model: '5-series',
        year: 2022,
        price: '42 000 000',
        specs: {
          type: 'Седан',
          drive: 'Передний привод',
          gearbox: 'АКПП',
          fuel: 'Бензин',
          volume: '4.4 литра',
          mileage: '2 000 км',
        },
        location: 'Сеул, Корея',
        id: '29',
      },
      {
        image: bmwPic,
        make: 'BMW',
        model: '5-series',
        year: 2022,
        price: '42 000 000',
        specs: {
          type: 'Седан',
          drive: 'Передний привод',
          gearbox: 'АКПП',
          fuel: 'Бензин',
          volume: '4.4 литра',
          mileage: '2 000 км',
        },
        location: 'Сеул, Корея',
        id: '30',
      },
      {
        image: bmwPic,
        make: 'BMW',
        model: '5-series',
        year: 2022,
        price: '42 000 000',
        specs: {
          type: 'Седан',
          drive: 'Передний привод',
          gearbox: 'АКПП',
          fuel: 'Бензин',
          volume: '4.4 литра',
          mileage: '2 000 км',
        },
        location: 'Сеул, Корея',
        id: '31',
      },
      {
        image: bmwPic,
        make: 'BMW',
        model: '5-series',
        year: 2022,
        price: '42 000 000',
        specs: {
          type: 'Седан',
          drive: 'Передний привод',
          gearbox: 'АКПП',
          fuel: 'Бензин',
          volume: '4.4 литра',
          mileage: '2 000 км',
        },
        location: 'Сеул, Корея',
        id: '32',
      },
      {
        image: bmwPic,
        make: 'BMW',
        model: '5-series',
        year: 2022,
        price: '42 000 000',
        specs: {
          type: 'Седан',
          drive: 'Передний привод',
          gearbox: 'АКПП',
          fuel: 'Бензин',
          volume: '4.4 литра',
          mileage: '2 000 км',
        },
        location: 'Сеул, Корея',
        id: '33',
      },
    ],
  },
];
